#!/usr/bin/env python3
#MISE description="Start Postgres and wait until it accepts connections"
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / ".scripts"))
from omashiki import compose, wait_for_db

compose("up", "db", "-d", "--wait")
wait_for_db()
