import Config

# Configure your database
# Host, user, password and database name are environment-overridable for the
# same reason the port already was: a multi-node install points every machine at
# one PostgreSQL, and only one of them has it on localhost. Defaults are the
# single-node Compose values, so nothing changes without the variables.
config :omashiki, Omashiki.Repo,
  username: System.get_env("OMASHIKI_DB_USER") || "postgres",
  password: System.get_env("OMASHIKI_DB_PASSWORD") || "postgres",
  hostname: System.get_env("OMASHIKI_DB_HOST") || "localhost",
  port: String.to_integer(System.get_env("OMASHIKI_DB_PORT") || "5432"),
  database: System.get_env("OMASHIKI_DB_NAME") || "omashiki_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Tunable for load testing: the default pool of 10 is exhausted well before
  # the container limit is, and a queue timeout surfaces as a 500 on job
  # submission rather than as backpressure.
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  queue_target: String.to_integer(System.get_env("POOL_QUEUE_TARGET") || "50"),
  queue_interval: String.to_integer(System.get_env("POOL_QUEUE_INTERVAL") || "1000")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :omashiki, OmashikiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "vh5B4AZ+oKh5S1IBm0+/4ouLoL/WJBDvq1caXOQCZPliI3AEbtEeE1JztGvKd1m6",
  # `--sourcemap=inline` is a dev-only debugging aid and is deliberately absent
  # from the shared esbuild profile in config.exs, so the watcher's output is
  # NOT what `assets.build` or `assets.deploy` emits. That divergence is only
  # safe because priv/static/assets is gitignored build output: never commit a
  # watcher-built bundle, or production ships a source map of dev sources.
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:omashiki, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:omashiki, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :omashiki, OmashikiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/omashiki_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for the LiveDashboard
config :omashiki, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
